const featuredProducts = [
  // ELECTRONICS CATEGORY - 6 products
  {
    id: 1,
    title: "Marshall Headphones",
    description: "Noise-cancelling, wireless, and high-fidelity sound quality.",
    price: 12999.99,
    originalPrice: 15999.99,
    discount: "35% OFF",
    image:
      "https://media.croma.com/image/upload/v1723054217/Croma%20Assets/Communication/Headphones%20and%20Earphones/Images/227824_0_fcnxfv.png",
    isNew: true,
    isBestSeller: true,
    rating: 4.5,
    reviews: 128,
    stockStatus: "In Stock",
    stockQuantity: 15,
    category: "Electronics",
    brand: "SoundPro",
    colors: [{ name: "Black", value: "black", hex: "#000000" }],
    sizes: ["Standard"],
    features: [
      "High-fidelity sound",
      "Noise cancellation",
      "Wireless connectivity",
    ],
    shipping: "Free shipping on orders over $50",
    returns: "30-day easy returns and exchanges",
    images: [
      "https://media.croma.com/image/upload/v1723054217/Croma%20Assets/Communication/Headphones%20and%20Earphones/Images/227824_0_fcnxfv.png",
    ],
  },
  {
    id: 7,
    title: 'Samsung 65" QLED TV',
    description:
      "Ultra HD 4K smart TV with stunning picture quality and built-in streaming apps.",
    price: 89999.99,
    originalPrice: 109999.99,
    discount: "18% OFF",
    image:
      "https://images.samsung.com/is/image/samsung/p6pim/in/qa65q70bakxxl/gallery/in-qled-q70b-qa65q70bakxxl-531161788?$650_519_PNG$",
    isNew: true,
    isBestSeller: false,
    rating: 4.7,
    reviews: 195,
    stockStatus: "In Stock",
    stockQuantity: 12,
    category: "Electronics",
    brand: "Samsung",
    colors: [{ name: "Black", value: "black", hex: "#000000" }],
    sizes: ["65 inch"],
    features: [
      "4K QLED Display",
      "Smart TV functionality",
      "Game Mode",
      "Voice Assistant",
    ],
    shipping: "Free shipping",
    returns: "14-day easy returns and exchanges",
    images: [
      "https://images.samsung.com/is/image/samsung/p6pim/in/qa65q70bakxxl/gallery/in-qled-q70b-qa65q70bakxxl-531161788?$650_519_PNG$",
    ],
  },
  {
    id: 8,
    title: "Apple MacBook Pro M3",
    description:
      "Powerful laptop with M3 chip, ideal for professionals and creatives.",
    price: 129999.99,
    originalPrice: 149999.99,
    discount: "13% OFF",
    image:
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/macbook-pro-space-black-select-202310?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1697311054290",
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 286,
    stockStatus: "Limited Stock",
    stockQuantity: 8,
    category: "Electronics",
    brand: "Apple",
    colors: [{ name: "Space Gray", value: "gray", hex: "#5E5E5E" }],
    sizes: ["14 inch"],
    features: ["M3 Chip", "16GB RAM", "512GB SSD", "Retina Display"],
    shipping: "Free shipping",
    returns: "14-day easy returns and exchanges",
    images: [
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/macbook-pro-space-black-select-202310?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1697311054290",
    ],
  },
  {
    id: 9,
    title: "Canon EOS R5 Camera",
    description: "Professional mirrorless camera with 45MP full-frame sensor.",
    price: 339999.99,
    originalPrice: 369999.99,
    discount: "8% OFF",
    image:
      "https://in.canon/media/image/2020/07/09/e90976e2414a459bb23f2c4c43f79155_EOS+R5_Front_RF24-105mm.png",
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 174,
    stockStatus: "In Stock",
    stockQuantity: 6,
    category: "Electronics",
    brand: "Canon",
    colors: [{ name: "Black", value: "black", hex: "#000000" }],
    sizes: ["Standard"],
    features: [
      "45MP Full-frame sensor",
      "8K video recording",
      "In-body stabilization",
      "Dual card slots",
    ],
    shipping: "Free shipping",
    returns: "14-day easy returns",
    images: [
      "https://in.canon/media/image/2020/07/09/e90976e2414a459bb23f2c4c43f79155_EOS+R5_Front_RF24-105mm.png",
    ],
  },
  {
    id: 10,
    title: "Bose Home Speaker 500",
    description:
      "Premium wireless smart speaker with immersive sound and voice control.",
    price: 29999.99,
    originalPrice: 34999.99,
    discount: "14% OFF",
    image:
      "https://assets.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/global/products/speakers/home_speaker_500/product_silo_images/HS500_Black_Hero.psd/jcr:content/renditions/cq5dam.web.600.600.png",
    isNew: false,
    isBestSeller: false,
    rating: 4.6,
    reviews: 215,
    stockStatus: "In Stock",
    stockQuantity: 20,
    category: "Electronics",
    brand: "Bose",
    colors: [{ name: "Silver", value: "silver", hex: "#C0C0C0" }],
    sizes: ["Standard"],
    features: [
      "360° sound",
      "Voice assistants",
      "Wi-Fi and Bluetooth",
      "Color LCD display",
    ],
    shipping: "Free shipping on orders over $50",
    returns: "30-day easy returns and exchanges",
    images: [
      "https://assets.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/global/products/speakers/home_speaker_500/product_silo_images/HS500_Black_Hero.psd/jcr:content/renditions/cq5dam.web.600.600.png",
    ],
  },
  {
    id: 11,
    title: "Logitech MX Master 3 Mouse",
    description:
      "Advanced wireless mouse with customizable buttons and ergonomic design.",
    price: 7999.99,
    originalPrice: 9999.99,
    discount: "20% OFF",
    image:
      "https://resource.logitech.com/content/dam/logitech/en/products/mice/mx-master-3s/gallery/mx-master-3s-mouse-top-pale-grey.png",
    isNew: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 312,
    stockStatus: "In Stock",
    stockQuantity: 35,
    category: "Electronics",
    brand: "Logitech",
    colors: [{ name: "Gray", value: "gray", hex: "#808080" }],
    sizes: ["Standard"],
    features: [
      "Electromagnetic scrolling",
      "Ergonomic design",
      "Multi-device control",
      "USB-C charging",
    ],
    shipping: "Free shipping on orders over $50",
    returns: "30-day easy returns and exchanges",
    images: [
      "https://resource.logitech.com/content/dam/logitech/en/products/mice/mx-master-3s/gallery/mx-master-3s-mouse-top-pale-grey.png",
    ],
  },

  // FOOTWEAR CATEGORY - 6 products
  {
    id: 2,
    title: "Nike Running Shoes",
    description: "Lightweight running shoes for daily fitness routines.",
    price: 5999.99,
    originalPrice: 7999.99,
    discount: "25% OFF",
    image:
      "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/12b4c855-4419-4764-9178-bbbe5a64e6a1/NIKE+ZOOMX+INVINCIBLE+RN+3+OLY.png",
    isNew: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 145,
    stockStatus: "In Stock",
    stockQuantity: 22,
    category: "Footwear",
    brand: "Nike",
    colors: [{ name: "Blue", value: "blue", hex: "#0000FF" }],
    sizes: ["8", "9", "10", "11"],
    features: ["Breathable mesh", "Durable sole", "Cushioned comfort"],
    shipping: "Free shipping on orders over $50",
    returns: "30-day easy returns and exchanges",
    images: [
      "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/12b4c855-4419-4764-9178-bbbe5a64e6a1/NIKE+ZOOMX+INVINCIBLE+RN+3+OLY.png",
    ],
  },
  {
    id: 12,
    title: "Adidas Ultraboost 22",
    description:
      "Premium running shoes with responsive cushioning and energy return.",
    price: 14999.99,
    originalPrice: 17999.99,
    discount: "17% OFF",
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/96a5f085ef1c4e509ac9aeea010755ff_9366/Ultraboost_22_Shoes_Black_GZ0127_01_standard.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 312,
    stockStatus: "In Stock",
    stockQuantity: 18,
    category: "Footwear",
    brand: "Adidas",
    colors: [{ name: "Black", value: "black", hex: "#000000" }],
    sizes: ["7", "8", "9", "10", "11", "12"],
    features: [
      "Boost midsole",
      "Primeknit upper",
      "Continental rubber outsole",
    ],
    shipping: "Free shipping on orders over $50",
    returns: "30-day easy returns",
    images: [
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/96a5f085ef1c4e509ac9aeea010755ff_9366/Ultraboost_22_Shoes_Black_GZ0127_01_standard.jpg",
    ],
  },
  {
    id: 13,
    title: "Puma RS-X Sneakers",
    description: "Retro-inspired chunky sneakers with bold design elements.",
    price: 8999.99,
    originalPrice: 10999.99,
    discount: "18% OFF",
    image:
      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/369579/01/sv01/fnd/IND/fmt/png/RS-X-Reinvention-Sneakers",
    isNew: true,
    isBestSeller: false,
    rating: 4.5,
    reviews: 178,
    stockStatus: "In Stock",
    stockQuantity: 25,
    category: "Footwear",
    brand: "Puma",
    colors: [
      { name: "White", value: "white", hex: "#FFFFFF" },
      { name: "Red", value: "red", hex: "#FF0000" },
    ],
    sizes: ["7", "8", "9", "10", "11"],
    features: [
      "Chunky silhouette",
      "Running System technology",
      "Mesh and leather upper",
    ],
    shipping: "Free shipping on orders over $50",
    returns: "30-day easy returns",
    images: [
      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/369579/01/sv01/fnd/IND/fmt/png/RS-X-Reinvention-Sneakers",
    ],
  },
  {
    id: 14,
    title: "Reebok Classic Leather",
    description: "Iconic lifestyle sneakers with timeless design and comfort.",
    price: 6999.99,
    originalPrice: 8499.99,
    discount: "18% OFF",
    image:
      "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/fd8fd539bb72438e9671abf1007911b3_9366/Classic_Leather_Shoes_White_49797_01_standard.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.6,
    reviews: 225,
    stockStatus: "In Stock",
    stockQuantity: 30,
    category: "Footwear",
    brand: "Reebok",
    colors: [{ name: "White", value: "white", hex: "#FFFFFF" }],
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    features: ["Leather upper", "EVA midsole", "High-abrasion rubber outsole"],
    shipping: "Free shipping on orders over $50",
    returns: "30-day easy returns",
    images: [
      "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/fd8fd539bb72438e9671abf1007911b3_9366/Classic_Leather_Shoes_White_49797_01_standard.jpg",
    ],
  },
  {
    id: 15,
    title: "New Balance 990v5",
    description:
      "Premium made-in-USA running shoes with superior cushioning and support.",
    price: 17999.99,
    originalPrice: 19999.99,
    discount: "10% OFF",
    image:
      "https://nb.scene7.com/is/image/NB/m990gl5_nb_02_i?$pdpflexf2$&wid=440&hei=440",
    isNew: false,
    isBestSeller: false,
    rating: 4.8,
    reviews: 156,
    stockStatus: "Limited Stock",
    stockQuantity: 12,
    category: "Footwear",
    brand: "New Balance",
    colors: [{ name: "Gray", value: "gray", hex: "#808080" }],
    sizes: ["8", "9", "10", "11", "12"],
    features: ["ENCAP midsole", "Blown rubber outsole", "Pigskin/mesh upper"],
    shipping: "Free shipping",
    returns: "30-day easy returns",
    images: [
      "https://nb.scene7.com/is/image/NB/m990gl5_nb_02_i?$pdpflexf2$&wid=440&hei=440",
    ],
  },
  {
    id: 16,
    title: "Birkenstock Arizona Sandals",
    description:
      "Classic two-strap sandals with anatomically shaped cork-latex footbed.",
    price: 8999.99,
    originalPrice: 9999.99,
    discount: "10% OFF",
    image: "https://images.birkenstock.com/images/1019115/1019115_side.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 283,
    stockStatus: "In Stock",
    stockQuantity: 28,
    category: "Footwear",
    brand: "Birkenstock",
    colors: [{ name: "Brown", value: "brown", hex: "#8B4513" }],
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    features: ["Cork footbed", "Adjustable buckles", "Suede upper"],
    shipping: "Free shipping on orders over $50",
    returns: "14-day easy returns",
    images: ["https://images.birkenstock.com/images/1019115/1019115_side.jpg"],
  },

  // HOME & FURNITURE CATEGORY - 6 products
  {
    id: 3,
    title: "Wooden Dining Table Set",
    description: "Elegant and modern 6-seater dining table set.",
    price: 18999.99,
    originalPrice: 24999.99,
    discount: "24% OFF",
    image:
      "https://rukminim1.flixcart.com/image/416/416/ktyp8cw0/dining-set/1/k/q/4-seater-brown-117-5x71-1-5x75-mas-dng-a4-4-8-cft-urbanwood-original-imag76y2ehwzhb5u.jpeg?q=70",
    isNew: false,
    isBestSeller: true,
    rating: 4.5,
    reviews: 98,
    stockStatus: "Limited Stock",
    stockQuantity: 8,
    category: "Home & Furniture",
    brand: "UrbanWood",
    colors: [{ name: "Brown", value: "brown", hex: "#8B4513" }],
    sizes: ["6-Seater"],
    features: ["Solid wood construction", "Modern design", "Easy assembly"],
    shipping: "Free delivery",
    returns: "7-day return policy",
    images: [
      "https://rukminim1.flixcart.com/image/416/416/ktyp8cw0/dining-set/1/k/q/4-seater-brown-117-5x71-1-5x75-mas-dng-a4-4-8-cft-urbanwood-original-imag76y2ehwzhb5u.jpeg?q=70",
    ],
  },
  {
    id: 17,
    title: "L-Shaped Sectional Sofa",
    description:
      "Contemporary L-shaped sofa with chaise lounge and premium upholstery.",
    price: 49999.99,
    originalPrice: 65999.99,
    discount: "24% OFF",
    image:
      "https://www.ikea.com/in/en/images/products/finnala-corner-sofa-5-seat-with-chaise-longue-gunnared-medium-grey__0814367_pe772427_s5.jpg",
    isNew: true,
    isBestSeller: true,
    rating: 4.7,
    reviews: 142,
    stockStatus: "In Stock",
    stockQuantity: 6,
    category: "Home & Furniture",
    brand: "ComfortPlus",
    colors: [{ name: "Gray", value: "gray", hex: "#808080" }],
    sizes: ["Standard"],
    features: [
      "Premium fabric",
      "High-density foam",
      "Removable covers",
      "Storage under chaise",
    ],
    shipping: "Free delivery and assembly",
    returns: "30-day return policy",
    images: [
      "https://www.ikea.com/in/en/images/products/finnala-corner-sofa-5-seat-with-chaise-longue-gunnared-medium-grey__0814367_pe772427_s5.jpg",
    ],
  },
  {
    id: 18,
    title: "King Size Platform Bed",
    description:
      "Modern king size platform bed with headboard and under-bed storage.",
    price: 32999.99,
    originalPrice: 38999.99,
    discount: "15% OFF",
    image:
      "https://www.ikea.com/au/en/images/products/malm-bed-frame-high-w-4-storage-boxes-white-luroey__1101959_pe866827_s5.jpg",
    isNew: false,
    isBestSeller: false,
    rating: 4.6,
    reviews: 118,
    stockStatus: "In Stock",
    stockQuantity: 9,
    category: "Home & Furniture",
    brand: "SleepHaven",
    colors: [
      { name: "White", value: "white", hex: "#FFFFFF" },
      { name: "Walnut", value: "walnut", hex: "#5C4033" },
    ],
    sizes: ["King"],
    features: [
      "Storage drawers",
      "Upholstered headboard",
      "Sturdy construction",
      "No box spring needed",
    ],
    shipping: "Free delivery and assembly",
    returns: "14-day return policy",
    images: [
      "https://www.ikea.com/au/en/images/products/malm-bed-frame-high-w-4-storage-boxes-white-luroey__1101959_pe866827_s5.jpg",
    ],
  },
  {
    id: 19,
    title: "Mid-Century Accent Chair",
    description:
      "Stylish mid-century inspired accent chair with solid wood legs.",
    price: 12999.99,
    originalPrice: 15999.99,
    discount: "19% OFF",
    image:
      "https://www.ikea.com/in/en/images/products/ekenaeset-armchair-hillared-anthracite__0986079_pe816883_s5.jpg",
    isNew: true,
    isBestSeller: true,
    rating: 4.7,
    reviews: 187,
    stockStatus: "In Stock",
    stockQuantity: 15,
    category: "Home & Furniture",
    brand: "ModernLiving",
    colors: [
      { name: "Blue", value: "blue", hex: "#4682B4" },
      { name: "Mustard", value: "mustard", hex: "#E1AD01" },
    ],
    sizes: ["Standard"],
    features: [
      "Solid wood frame",
      "High-density foam",
      "Premium upholstery",
      "Easy assembly",
    ],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: [
      "https://www.ikea.com/in/en/images/products/ekenaeset-armchair-hillared-anthracite__0986079_pe816883_s5.jpg",
    ],
  },
  {
    id: 20,
    title: "Bookshelf with Storage",
    description: "Modern 5-tier bookshelf with multiple storage compartments.",
    price: 8999.99,
    originalPrice: 10999.99,
    discount: "18% OFF",
    image:
      "https://www.ikea.com/in/en/images/products/billy-bookcase-with-doors-dark-blue__0850024_pe725976_s5.jpg",
    isNew: false,
    isBestSeller: false,
    rating: 4.5,
    reviews: 156,
    stockStatus: "In Stock",
    stockQuantity: 22,
    category: "Home & Furniture",
    brand: "HomeEssentials",
    colors: [
      { name: "White", value: "white", hex: "#FFFFFF" },
      { name: "Espresso", value: "espresso", hex: "#3C2218" },
    ],
    sizes: ["Standard"],
    features: [
      "Adjustable shelves",
      "Easy assembly",
      "Solid construction",
      "Wall anchor included",
    ],
    shipping: "Free shipping on orders over $50",
    returns: "14-day return policy",
    images: [
      "https://www.ikea.com/in/en/images/products/billy-bookcase-with-doors-dark-blue__0850024_pe725976_s5.jpg",
    ],
  },
  {
    id: 21,
    title: "Marble Top Coffee Table",
    description:
      "Elegant coffee table with genuine marble top and metal frame.",
    price: 15999.99,
    originalPrice: 19999.99,
    discount: "20% OFF",
    image:
      "https://www.ikea.com/in/en/images/products/borgeby-coffee-table-black__0735092_pe739905_s5.jpg",
    isNew: true,
    isBestSeller: false,
    rating: 4.8,
    reviews: 94,
    stockStatus: "Limited Stock",
    stockQuantity: 7,
    category: "Home & Furniture",
    brand: "LuxuryLiving",
    colors: [
      { name: "White Marble/Gold", value: "white/gold", hex: "#FFD700" },
    ],
    sizes: ["Standard"],
    features: [
      "Genuine marble top",
      "Gold-finished steel frame",
      "Non-marking feet",
      "Easy assembly",
    ],
    shipping: "Free white glove delivery",
    returns: "7-day return policy",
    images: [
      "https://www.ikea.com/in/en/images/products/borgeby-coffee-table-black__0735092_pe739905_s5.jpg",
    ],
  },

  // PERFUMES CATEGORY - 6 products
  {
    id: 4,
    title: "Versace Eros Perfume",
    description: "Luxurious fragrance for men with a long-lasting scent.",
    price: 6499.99,
    originalPrice: 7999.99,
    discount: "20% OFF",
    image: "https://m.media-amazon.com/images/I/71O1O1gRdjL._SL1500_.jpg",
    isNew: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 182,
    stockStatus: "In Stock",
    stockQuantity: 30,
    category: "Perfumes",
    brand: "Versace",
    colors: [{ name: "Blue", value: "blue", hex: "#4682B4" }],
    sizes: ["100ml"],
    features: ["Eau de Parfum", "Long-lasting fragrance"],
    shipping: "Free shipping",
    returns: "7-day return policy",
    images: ["https://m.media-amazon.com/images/I/71O1O1gRdjL._SL1500_.jpg"],
  },
  {
    id: 22,
    title: "Chanel No. 5",
    description:
      "Iconic floral-aldehyde fragrance for women with timeless appeal.",
    price: 8999.99,
    originalPrice: 9999.99,
    discount: "10% OFF",
    image:
      "https://www.chanel.com/images/w_1920,h_1920,c_crop/q_auto,f_auto/w_1240/chanel-5-eau-de-parfum-spray-3-4fl-oz--packshot-default-125530-8848376676382.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 312,
    stockStatus: "In Stock",
    stockQuantity: 25,
    category: "Perfumes",
    brand: "Chanel",
    colors: [{ name: "Clear", value: "clear", hex: "#FFFFFF" }],
    sizes: ["50ml", "100ml"],
    features: [
      "Eau de Parfum",
      "Long-lasting fragrance",
      "Iconic bottle design",
    ],
    shipping: "Free shipping",
    returns: "14-day return policy",
    images: [
      "https://www.chanel.com/images/w_1920,h_1920,c_crop/q_auto,f_auto/w_1240/chanel-5-eau-de-parfum-spray-3-4fl-oz--packshot-default-125530-8848376676382.jpg",
    ],
  },
  {
    id: 23,
    title: "Dior Sauvage",
    description:
      "Fresh and bold masculine fragrance with notes of bergamot and ambroxan.",
    price: 7899.99,
    originalPrice: 8999.99,
    discount: "12% OFF",
    image:
      "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwfa3938fd/Y0997004/Y0997004_C099700485_E01_GHC.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 287,
    stockStatus: "In Stock",
    stockQuantity: 35,
    category: "Perfumes",
    brand: "Dior",
    colors: [{ name: "Clear", value: "clear", hex: "#FFFFFF" }],
    sizes: ["60ml", "100ml", "200ml"],
    features: ["Eau de Toilette", "Long-lasting fragrance", "Signature scent"],
    shipping: "Free shipping",
    returns: "14-day return policy",
    images: [
      "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwfa3938fd/Y0997004/Y0997004_C099700485_E01_GHC.jpg",
    ],
  },
  {
    id: 24,
    title: "Tom Ford Black Orchid",
    description:
      "Luxurious unisex fragrance with rich, dark accords and sensual florals.",
    price: 12999.99,
    originalPrice: 14999.99,
    discount: "13% OFF",
    image:
      "https://www.tomford.com/dw/image/v2/AAHP_PRD/on/demandware.static/-/Sites-tomford-master-catalog/default/dw50f12464/original/PROD_T37X_01_FRAGRANCE.jpg",
    isNew: false,
    isBestSeller: false,
    rating: 4.7,
    reviews: 165,
    stockStatus: "Limited Stock",
    stockQuantity: 12,
    category: "Perfumes",
    brand: "Tom Ford",
    colors: [{ name: "Black", value: "black", hex: "#000000" }],
    sizes: ["50ml", "100ml"],
    features: [
      "Eau de Parfum",
      "Long-lasting fragrance",
      "Sensual and sophisticated",
    ],
    shipping: "Free shipping",
    returns: "14-day return policy",
    images: [
      "https://www.tomford.com/dw/image/v2/AAHP_PRD/on/demandware.static/-/Sites-tomford-master-catalog/default/dw50f12464/original/PROD_T37X_01_FRAGRANCE.jpg",
    ],
  },
  {
    id: 25,
    title: "Yves Saint Laurent Libre",
    description:
      "Bold and feminine fragrance with notes of lavender and orange blossom.",
    price: 6999.99,
    originalPrice: 7999.99,
    discount: "13% OFF",
    image:
      "https://www.yslbeautyus.com/dw/image/v2/BBXZ_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw7c0d6f3c/fragrance/YSL-Fragrance-Libre-EDP-50ml-3614272991918.jpg?sw=800&sh=800&sm=fit",
    isNew: false,
    isBestSeller: false,
    rating: 4.6,
    reviews: 198,
    stockStatus: "In Stock",
    stockQuantity: 20,
    category: "Perfumes",
    brand: "Yves Saint Laurent",
    colors: [{ name: "Clear", value: "clear", hex: "#FFFFFF" }],
    sizes: ["50ml", "90ml"],
    features: ["Eau de Parfum", "Long-lasting fragrance", "Bold and sensual"],
    shipping: "Free shipping",
    returns: "14-day return policy",
    images: [
      "https://www.yslbeautyus.com/dw/image/v2/BBXZ_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw7c0d6f3c/fragrance/YSL-Fragrance-Libre-EDP-50ml-3614272991918.jpg?sw=800&sh=800&sm=fit",
    ],
  },
  {
    id: 26,
    title: "Gucci Guilty Pour Homme",
    description:
      "Modern and masculine fragrance with notes of lavender and patchouli.",
    price: 8999.99,
    originalPrice: 9999.99,
    discount: "10% OFF",
    image:
      "https://www.gucci.com/images/ecommerce/styles_new/ecommerce/styles_new/161719I87IN1000_1000_001_100_0000_Light-Gucci-Guilty-Pour-Homme-50ml-EDT-1.jpg",
    isNew: false,
    isBestSeller: false,
    rating: 4.7,
    reviews: 212,
    stockStatus: "In Stock",
    stockQuantity: 25,
    category: "Perfumes",
    brand: "Gucci",
    colors: [{ name: "Clear", value: "clear", hex: "#FFFFFF" }],
    sizes: ["50ml", "90ml"],
    features: ["Eau de Toilette", "Long-lasting fragrance", "Modern and bold"],
    shipping: "Free shipping",
    returns: "14-day return policy",
    images: [
      "https://www.gucci.com/images/ecommerce/styles_new/ecommerce/styles_new/161719I87IN1000_1000_001_100_0000_Light-Gucci-Guilty-Pour-Homme-50ml-EDT-1.jpg",
    ],
  },

  // CLOTHING CATEGORY - 6 products

  {
    id: 217,
    title: "Nike Air Max 270",
    description: "Stylish and comfortable sneakers with superior cushioning.",
    price: 14999.99,
    originalPrice: 16999.99,
    discount: "12% OFF",
    image:
      "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/abc123/nike-air-max-270.jpg",
    isNew: true,
    isBestSeller: true,
    rating: 4.8,
    reviews: 340,
    stockStatus: "In Stock",
    stockQuantity: 50,
    category: "Clothing",
    brand: "Nike",
    colors: [{ name: "Black", value: "black", hex: "#000000" }],
    sizes: ["US 8", "US 9", "US 10", "US 11"],
    features: [
      "Breathable mesh upper",
      "Responsive cushioning",
      "Durable outsole",
    ],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: [
      "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/abc123/nike-air-max-270.jpg",
    ],
  },
  {
    id: 218,
    title: "Adidas Ultraboost 22",
    description:
      "High-performance running shoes with responsive Boost midsole.",
    price: 17999.99,
    originalPrice: 19999.99,
    discount: "10% OFF",
    image: "https://assets.adidas.com/images/adidas-ultraboost-22.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 280,
    stockStatus: "In Stock",
    stockQuantity: 40,
    category: "Clothing",
    brand: "Adidas",
    colors: [{ name: "White", value: "white", hex: "#FFFFFF" }],
    sizes: ["US 7", "US 8", "US 9", "US 10"],
    features: ["Primeknit upper", "Energy return", "Sock-like fit"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://assets.adidas.com/images/adidas-ultraboost-22.jpg"],
  },
  {
    id: 219,
    title: "Levi's 501 Original Jeans",
    description: "Classic straight-fit jeans with a timeless look.",
    price: 6999.99,
    originalPrice: 7999.99,
    discount: "13% OFF",
    image: "https://levi.com/images/levis-501-jeans.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.6,
    reviews: 420,
    stockStatus: "In Stock",
    stockQuantity: 30,
    category: "Clothing",
    brand: "Levi's",
    colors: [{ name: "Denim Blue", value: "blue", hex: "#1E90FF" }],
    sizes: ["30", "32", "34", "36"],
    features: ["Button fly", "Straight leg", "Durable denim"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://levi.com/images/levis-501-jeans.jpg"],
  },
  {
    id: 220,
    title: "The North Face Puffer Jacket",
    description: "Warm and stylish insulated jacket for cold weather.",
    price: 19999.99,
    originalPrice: 22999.99,
    discount: "13% OFF",
    image: "https://thenorthface.com/images/puffer-jacket.jpg",
    isNew: true,
    isBestSeller: false,
    rating: 4.8,
    reviews: 150,
    stockStatus: "In Stock",
    stockQuantity: 20,
    category: "Clothing",
    brand: "The North Face",
    colors: [{ name: "Red", value: "red", hex: "#FF0000" }],
    sizes: ["S", "M", "L", "XL"],
    features: ["Water-resistant", "Lightweight insulation", "Zipper closure"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://thenorthface.com/images/puffer-jacket.jpg"],
  },
  {
    id: 221,
    title: "Polo Ralph Lauren T-Shirt",
    description: "Classic cotton t-shirt with embroidered pony logo.",
    price: 3999.99,
    originalPrice: 4999.99,
    discount: "20% OFF",
    image: "https://ralphlauren.com/images/polo-tshirt.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.5,
    reviews: 310,
    stockStatus: "In Stock",
    stockQuantity: 60,
    category: "Clothing",
    brand: "Polo Ralph Lauren",
    colors: [{ name: "Navy Blue", value: "navy", hex: "#000080" }],
    sizes: ["S", "M", "L", "XL", "XXL"],
    features: ["100% cotton", "Soft and breathable", "Crew neck"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://ralphlauren.com/images/polo-tshirt.jpg"],
  },
  {
    id: 222,
    title: "Hugo Boss Slim Fit Suit",
    description: "Elegant slim-fit suit for formal occasions.",
    price: 59999.99,
    originalPrice: 69999.99,
    discount: "14% OFF",
    image: "https://hugoboss.com/images/slim-fit-suit.jpg",
    isNew: false,
    isBestSeller: false,
    rating: 4.9,
    reviews: 95,
    stockStatus: "In Stock",
    stockQuantity: 15,
    category: "Clothing",
    brand: "Hugo Boss",
    colors: [{ name: "Charcoal Gray", value: "gray", hex: "#808080" }],
    sizes: ["38R", "40R", "42R", "44R"],
    features: ["Wool blend", "Slim fit", "Notch lapel"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://hugoboss.com/images/slim-fit-suit.jpg"],
  },

  // BOOKS CATEGORY - 6 products

  {
    id: 300,
    title: "The Great Gatsby",
    description:
      "A classic novel by F. Scott Fitzgerald exploring wealth, love, and the American Dream.",
    price: 799.99,
    originalPrice: 999.99,
    discount: "20% OFF",
    image: "https://example.com/images/the-great-gatsby.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 1250,
    stockStatus: "In Stock",
    stockQuantity: 100,
    category: "Books",
    author: "F. Scott Fitzgerald",
    publisher: "Scribner",
    format: ["Hardcover", "Paperback", "E-book"],
    languages: ["English"],
    features: [
      "Classic literature",
      "Timeless storytelling",
      "Historical fiction",
    ],
    shipping: "Free shipping",
    returns: "15-day return policy",
    images: ["https://example.com/images/the-great-gatsby.jpg"],
  },
  {
    id: 301,
    title: "Atomic Habits",
    description:
      "A self-help book by James Clear that explores habit-building strategies for success.",
    price: 1299.99,
    originalPrice: 1499.99,
    discount: "13% OFF",
    image: "https://example.com/images/atomic-habits.jpg",
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 3100,
    stockStatus: "In Stock",
    stockQuantity: 200,
    category: "Books",
    author: "James Clear",
    publisher: "Penguin Random House",
    format: ["Hardcover", "Paperback", "E-book", "Audiobook"],
    languages: ["English"],
    features: [
      "Personal development",
      "Productivity tips",
      "Behavioral psychology",
    ],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/atomic-habits.jpg"],
  },
  {
    id: 302,
    title: "1984",
    description:
      "A dystopian novel by George Orwell that delves into themes of totalitarianism and surveillance.",
    price: 699.99,
    originalPrice: 899.99,
    discount: "22% OFF",
    image: "https://example.com/images/1984.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 1800,
    stockStatus: "In Stock",
    stockQuantity: 150,
    category: "Books",
    author: "George Orwell",
    publisher: "Harvill Secker",
    format: ["Hardcover", "Paperback", "E-book", "Audiobook"],
    languages: ["English"],
    features: ["Political fiction", "Dystopian themes", "Thought-provoking"],
    shipping: "Free shipping",
    returns: "15-day return policy",
    images: ["https://example.com/images/1984.jpg"],
  },
  {
    id: 303,
    title: "The Alchemist",
    description:
      "A philosophical novel by Paulo Coelho about following one's dreams and destiny.",
    price: 899.99,
    originalPrice: 1099.99,
    discount: "18% OFF",
    image: "https://example.com/images/the-alchemist.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 2700,
    stockStatus: "In Stock",
    stockQuantity: 120,
    category: "Books",
    author: "Paulo Coelho",
    publisher: "HarperOne",
    format: ["Hardcover", "Paperback", "E-book"],
    languages: ["English", "Portuguese"],
    features: ["Inspirational story", "Spiritual journey", "Self-discovery"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/the-alchemist.jpg"],
  },
  {
    id: 304,
    title: "Sapiens: A Brief History of Humankind",
    description:
      "A bestselling book by Yuval Noah Harari exploring the history of human civilization.",
    price: 1599.99,
    originalPrice: 1799.99,
    discount: "11% OFF",
    image: "https://example.com/images/sapiens.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 3200,
    stockStatus: "In Stock",
    stockQuantity: 180,
    category: "Books",
    author: "Yuval Noah Harari",
    publisher: "Harper",
    format: ["Hardcover", "Paperback", "E-book", "Audiobook"],
    languages: ["English"],
    features: ["History", "Anthropology", "Thought-provoking insights"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/sapiens.jpg"],
  },
  {
    id: 305,
    title: "Harry Potter and the Sorcerer's Stone",
    description:
      "The first book in the legendary fantasy series by J.K. Rowling.",
    price: 1199.99,
    originalPrice: 1399.99,
    discount: "14% OFF",
    image: "https://example.com/images/harry-potter-1.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 5500,
    stockStatus: "In Stock",
    stockQuantity: 300,
    category: "Books",
    author: "J.K. Rowling",
    publisher: "Bloomsbury",
    format: ["Hardcover", "Paperback", "E-book", "Audiobook"],
    languages: ["English"],
    features: ["Fantasy", "Adventure", "Magic"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/harry-potter-1.jpg"],
  },

  // HEALTH & WELLNESS CATEGORY - 6 products

  {
    id: 400,
    title: "L'Oréal Revitalift Night Cream",
    description:
      "Anti-aging night cream with Pro-Retinol and Centella Asiatica for firmer skin.",
    price: 2499.99,
    originalPrice: 2999.99,
    discount: "17% OFF",
    image: "https://example.com/images/loreal-revitalift.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 680,
    stockStatus: "In Stock",
    stockQuantity: 80,
    category: "Health and Beauty",
    brand: "L'Oréal",
    features: ["Anti-aging formula", "Hydrating", "Dermatologically tested"],
    shipping: "Free shipping",
    returns: "15-day return policy",
    images: ["https://example.com/images/loreal-revitalift.jpg"],
  },
  {
    id: 401,
    title: "Neutrogena Hydro Boost Water Gel",
    description:
      "Lightweight moisturizer with hyaluronic acid for intense hydration.",
    price: 1899.99,
    originalPrice: 2199.99,
    discount: "14% OFF",
    image: "https://example.com/images/neutrogena-hydroboost.jpg",
    isNew: true,
    isBestSeller: true,
    rating: 4.8,
    reviews: 1250,
    stockStatus: "In Stock",
    stockQuantity: 100,
    category: "Health and Beauty",
    brand: "Neutrogena",
    features: ["Hydrates skin", "Oil-free", "Suitable for all skin types"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/neutrogena-hydroboost.jpg"],
  },
  {
    id: 402,
    title: "Maybelline Lash Sensational Mascara",
    description: "Lengthening and volumizing mascara for fuller lashes.",
    price: 999.99,
    originalPrice: 1299.99,
    discount: "23% OFF",
    image: "https://example.com/images/maybelline-mascara.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.6,
    reviews: 2200,
    stockStatus: "In Stock",
    stockQuantity: 150,
    category: "Health and Beauty",
    brand: "Maybelline",
    features: ["Long-lasting", "Smudge-proof", "Ophthalmologist tested"],
    shipping: "Free shipping",
    returns: "15-day return policy",
    images: ["https://example.com/images/maybelline-mascara.jpg"],
  },
  {
    id: 403,
    title: "CeraVe Hydrating Facial Cleanser",
    description:
      "Gentle face wash with ceramides and hyaluronic acid for dry skin.",
    price: 1599.99,
    originalPrice: 1799.99,
    discount: "11% OFF",
    image: "https://example.com/images/cerave-cleanser.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 1850,
    stockStatus: "In Stock",
    stockQuantity: 120,
    category: "Health and Beauty",
    brand: "CeraVe",
    features: ["Non-foaming", "Fragrance-free", "Dermatologist recommended"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/cerave-cleanser.jpg"],
  },
  {
    id: 404,
    title: "OGX Argan Oil of Morocco Shampoo",
    description:
      "Nourishing shampoo infused with argan oil for smooth, shiny hair.",
    price: 1299.99,
    originalPrice: 1499.99,
    discount: "13% OFF",
    image: "https://example.com/images/ogx-argan-shampoo.jpg",
    isNew: true,
    isBestSeller: false,
    rating: 4.7,
    reviews: 900,
    stockStatus: "In Stock",
    stockQuantity: 75,
    category: "Health and Beauty",
    brand: "OGX",
    features: ["Moisturizing", "Sulfate-free", "For all hair types"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/ogx-argan-shampoo.jpg"],
  },
  {
    id: 405,
    title: "Philips Norelco Electric Shaver 3800",
    description: "Wet & dry shaver with comfort cut blades and pop-up trimmer.",
    price: 4999.99,
    originalPrice: 5499.99,
    discount: "9% OFF",
    image: "https://example.com/images/philips-shaver.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 1300,
    stockStatus: "In Stock",
    stockQuantity: 50,
    category: "Health and Beauty",
    brand: "Philips",
    features: ["Rechargeable", "Waterproof", "Ergonomic design"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/philips-shaver.jpg"],
  },

  {
    id: 500,
    title: "LEGO City Police Station",
    description:
      "Exciting LEGO building set featuring a police station, vehicles, and minifigures.",
    price: 5999.99,
    originalPrice: 6999.99,
    discount: "14% OFF",
    image: "https://example.com/images/lego-police-station.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 1450,
    stockStatus: "In Stock",
    stockQuantity: 80,
    category: "Toys",
    brand: "LEGO",
    ageGroup: "6+ years",
    features: ["Interactive play", "Creative building", "Includes minifigures"],
    shipping: "Free shipping",
    returns: "15-day return policy",
    images: ["https://example.com/images/lego-police-station.jpg"],
  },
  {
    id: 501,
    title: "Hot Wheels Ultimate Garage",
    description:
      "A multi-level parking and racing playset with exciting Hot Wheels cars.",
    price: 4999.99,
    originalPrice: 5499.99,
    discount: "9% OFF",
    image: "https://example.com/images/hot-wheels-garage.jpg",
    isNew: true,
    isBestSeller: true,
    rating: 4.7,
    reviews: 2100,
    stockStatus: "In Stock",
    stockQuantity: 100,
    category: "Toys",
    brand: "Hot Wheels",
    ageGroup: "5+ years",
    features: [
      "Multi-level racing",
      "Includes Hot Wheels cars",
      "Durable and fun",
    ],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/hot-wheels-garage.jpg"],
  },
  {
    id: 502,
    title: "Barbie Dreamhouse Playset",
    description:
      "A luxurious Barbie playhouse with furniture, elevator, and accessories.",
    price: 7999.99,
    originalPrice: 8999.99,
    discount: "11% OFF",
    image: "https://example.com/images/barbie-dreamhouse.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 3200,
    stockStatus: "In Stock",
    stockQuantity: 50,
    category: "Toys",
    brand: "Barbie",
    ageGroup: "3+ years",
    features: [
      "Fully furnished",
      "Interactive elevator",
      "Includes Barbie accessories",
    ],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/barbie-dreamhouse.jpg"],
  },
  {
    id: 503,
    title: "NERF Elite 2.0 Blaster",
    description:
      "High-performance foam dart blaster for thrilling outdoor battles.",
    price: 1999.99,
    originalPrice: 2499.99,
    discount: "20% OFF",
    image: "https://example.com/images/nerf-blaster.jpg",
    isNew: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 1850,
    stockStatus: "In Stock",
    stockQuantity: 120,
    category: "Toys",
    brand: "NERF",
    ageGroup: "8+ years",
    features: [
      "High-speed shooting",
      "Includes foam darts",
      "Lightweight design",
    ],
    shipping: "Free shipping",
    returns: "15-day return policy",
    images: ["https://example.com/images/nerf-blaster.jpg"],
  },
  {
    id: 504,
    title: "Fisher-Price Laugh & Learn Smart Stages Puppy",
    description:
      "Educational plush toy with interactive features for early learning.",
    price: 1499.99,
    originalPrice: 1799.99,
    discount: "17% OFF",
    image: "https://example.com/images/fisher-price-puppy.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 2500,
    stockStatus: "In Stock",
    stockQuantity: 90,
    category: "Toys",
    brand: "Fisher-Price",
    ageGroup: "6 months - 3 years",
    features: [
      "Interactive buttons",
      "Teaches ABCs & numbers",
      "Soft and cuddly",
    ],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/fisher-price-puppy.jpg"],
  },
  {
    id: 505,
    title: "Monopoly Classic Board Game",
    description: "A timeless board game for family fun and strategic play.",
    price: 2999.99,
    originalPrice: 3499.99,
    discount: "14% OFF",
    image: "https://example.com/images/monopoly-game.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviews: 4100,
    stockStatus: "In Stock",
    stockQuantity: 200,
    category: "Toys",
    brand: "Hasbro",
    ageGroup: "8+ years",
    features: [
      "Classic gameplay",
      "Family-friendly",
      "Encourages strategic thinking",
    ],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/monopoly-game.jpg"],
  },

  // SPORTS - 6 products

  {
    id: 600,
    title: "CEAT Gripp Master English Willow Cricket Bat",
    description:
      "Professional-grade English willow bat for powerful shots and superior grip.",
    price: 7499.99,
    originalPrice: 8499.99,
    discount: "12% OFF",
    image: "https://example.com/images/ceat-cricket-bat.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 850,
    stockStatus: "In Stock",
    stockQuantity: 40,
    category: "Sports",
    brand: "CEAT",
    features: [
      "Premium English willow",
      "Superior grip",
      "Lightweight for better control",
    ],
    shipping: "Free shipping",
    returns: "15-day return policy",
    images: ["https://example.com/images/ceat-cricket-bat.jpg"],
  },
  {
    id: 601,
    title: "Nike Mercurial Superfly 8 Soccer Cleats",
    description:
      "High-performance soccer cleats designed for speed and agility on the field.",
    price: 8999.99,
    originalPrice: 9999.99,
    discount: "10% OFF",
    image: "https://example.com/images/nike-soccer-cleats.jpg",
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 1450,
    stockStatus: "In Stock",
    stockQuantity: 60,
    category: "Sports",
    brand: "Nike",
    features: [
      "Lightweight design",
      "Enhanced grip",
      "Durable synthetic upper",
    ],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/nike-soccer-cleats.jpg"],
  },
  {
    id: 602,
    title: "Yonex Astrox 100ZZ Badminton Racket",
    description:
      "Premium badminton racket with advanced technology for precision and power.",
    price: 10999.99,
    originalPrice: 12499.99,
    discount: "12% OFF",
    image: "https://example.com/images/yonex-badminton-racket.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 750,
    stockStatus: "In Stock",
    stockQuantity: 30,
    category: "Sports",
    brand: "Yonex",
    features: ["Ultra-lightweight", "Graphite frame", "Enhanced smash power"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/yonex-badminton-racket.jpg"],
  },
  {
    id: 603,
    title: "Spalding NBA Official Basketball",
    description:
      "Official size and weight basketball used in professional games.",
    price: 3499.99,
    originalPrice: 3999.99,
    discount: "13% OFF",
    image: "https://example.com/images/spalding-nba-basketball.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviews: 1300,
    stockStatus: "In Stock",
    stockQuantity: 70,
    category: "Sports",
    brand: "Spalding",
    features: [
      "Official NBA design",
      "Superior grip",
      "Durable synthetic leather",
    ],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/spalding-nba-basketball.jpg"],
  },
  {
    id: 604,
    title: "Adidas Training Gym Gloves",
    description:
      "Padded gym gloves for extra grip and wrist support during workouts.",
    price: 1299.99,
    originalPrice: 1599.99,
    discount: "19% OFF",
    image: "https://example.com/images/adidas-gym-gloves.jpg",
    isNew: true,
    isBestSeller: false,
    rating: 4.6,
    reviews: 600,
    stockStatus: "In Stock",
    stockQuantity: 90,
    category: "Sports",
    brand: "Adidas",
    features: ["Breathable material", "Strong grip", "Adjustable wrist straps"],
    shipping: "Free shipping",
    returns: "15-day return policy",
    images: ["https://example.com/images/adidas-gym-gloves.jpg"],
  },
  {
    id: 605,
    title: "Nivia Storm Football",
    description:
      "Durable football with superior grip and control for all weather conditions.",
    price: 999.99,
    originalPrice: 1299.99,
    discount: "23% OFF",
    image: "https://example.com/images/nivia-football.jpg",
    isNew: false,
    isBestSeller: true,
    rating: 4.7,
    reviews: 1100,
    stockStatus: "In Stock",
    stockQuantity: 120,
    category: "Sports",
    brand: "Nivia",
    features: ["Water-resistant", "Durable outer layer", "Soft touch feel"],
    shipping: "Free shipping",
    returns: "30-day return policy",
    images: ["https://example.com/images/nivia-football.jpg"],
  },
];

export default featuredProducts;
